spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #使用服务发现路由
      routes:
        - id: service-hosp #设置路由id
          predicates: Path=/*/hosp/** #设置路由断言,代理serverId.为 auth-service 的/auth/路径
          uri: lb://service-hosp #设置路由的uri
        - id: service-cmn
          predicates: Path=/*/cmn/**
          uri: lb://service-cmn
        - id: service-user
          predicates: Path=/*/user/**
          uri: lb://service-user
        - id: service-msm
          predicates: Path=/*/msm/**
          uri: lb://service-msm
        - id: service-user
          predicates:
            - Path=/*/ucenter/**,/oauth/**
          uri: lb://service-user
        - id: service-oss
          predicates: Path=/*/oss/**
          uri: lb://service-oss
        - id: service-order
          predicates: Path=/*/order/**
          uri: lb://service-order
