spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #使用服务发现路由
      routes:
        - id: service-hosp #设置路由id
          predicates: Path=/*/hosp/** #设置路由断言,代理serverId.为 auth-service 的/auth/路径
          uri: lb://service-hosp #设置路由的uri
        - id: service-cmn
          predicates: Path=/*/cmn/**
          uri: lb://service-cmn